import { createContext, useContext } from 'react'

export const LanguageContext = createContext('en')
export const useLanguage = () => useContext(LanguageContext)
export const useT = () => {
  const language = useLanguage()
  return (key, values) => translate(language, key, values)
}

const strings = {
  hi: {
    Demo: 'डेमो',
    'Store desk': 'स्टोर डेस्क',
    'Available cash': 'उपलब्ध नकद',
    Free: 'फ्री',
    'Tap to upgrade · ₹499/mo': 'अपग्रेड करें · ₹499/माह',
    'My store': 'मेरा स्टोर',
    'Demo store': 'डेमो स्टोर',
    'Store overview': 'स्टोर का हाल',
    'Your business at a glance': 'आपके बिज़नेस की एक झलक',
    'Needs attention': 'ध्यान देने की ज़रूरत',
    'On track': 'सब ठीक है',
    'Revenue at risk': 'जोखिम में बिक्री',
    'Potential sales · next 7 days': 'संभावित बिक्री · अगले 7 दिन',
    'Items at risk': 'जोखिम वाले आइटम',
    'Stock may run low soon': 'स्टॉक जल्द कम हो सकता है',
    'All listed items look covered': 'सभी आइटम का स्टॉक ठीक है',
    'Daily revenue': 'रोज़ की बिक्री',
    'A two-week view of your sales': 'पिछले 14 दिनों की बिक्री',
    '14 days': '14 दिन',
    'Create restock plan': 'रीस्टॉक प्लान बनाएं',
    'Preparing your restock plan…': 'रीस्टॉक प्लान तैयार हो रहा है…',
    'Restock plan ready — review the suggested order below': 'रीस्टॉक प्लान तैयार है — नीचे ऑर्डर देखें',
    'All items are well-stocked!': 'सभी आइटम का स्टॉक पर्याप्त है!',
    'Analysis failed': 'विश्लेषण पूरा नहीं हुआ',
    'Approval failed': 'ऑर्डर मंज़ूर नहीं हो पाया',
    'Rejection failed': 'ऑर्डर खारिज नहीं हो पाया',
    'Plan update failed': 'प्लान अपडेट नहीं हुआ',
    'Reset failed': 'डेमो रीसेट नहीं हुआ',
    'Orders placed with {count} distributor(s) ✓': '{count} सप्लायर को ऑर्डर भेजा ✓',
    ' · Loan ₹{amount} disbursed ✓': ' · ₹{amount} का लोन जारी ✓',
    ' · Cash ₹{amount}': ' · नकद ₹{amount}',
    'Demo reset ✓': 'डेमो रीसेट हो गया ✓',
    'Premium activated! ₹499/mo': 'प्रीमियम चालू हुआ! ₹499/माह',
    'Switched to Free plan': 'फ्री प्लान पर स्विच किया',
    'Proposal dismissed': 'प्रस्ताव हटा दिया गया',
    'Analysis complete — review the restock alert below': 'विश्लेषण पूरा — नीचे रीस्टॉक अलर्ट देखें',
    'this week': 'इस हफ्ते',
    'of {total} total': 'कुल {total} में से',
    Inventory: 'इन्वेंटरी',
    'Tap an item to view its forecast': 'फोरकास्ट देखने के लिए आइटम चुनें',
    '{count} items': '{count} आइटम',
    Incoming: 'आ रहा है',
    'Out tomorrow!': 'कल स्टॉक खत्म!',
    '≈{days} days': 'लगभग {days} दिन',
    'arriving {date}': '{date} को आएगा',
    'Restock alert': 'रीस्टॉक अलर्ट',
    'Review your suggested order': 'सुझाया गया ऑर्डर देखें',
    'Preview notification': 'नोटिफिकेशन देखें',
    Listen: 'सुनें',
    'Order ₹{amount}': 'ऑर्डर ₹{amount}',
    'Dismiss': 'हटाएं',
    'Approve & Fund': 'मंज़ूर करें',
    'Placing orders…': 'ऑर्डर भेजे जा रहे हैं…',
    'Order Details': 'ऑर्डर की जानकारी',
    Subtotal: 'सबटोटल',
    'Platform fee (1%)': 'प्लेटफ़ॉर्म शुल्क (1%)',
    Total: 'कुल',
    'Cash available': 'उपलब्ध नकद',
    'Cash gap': 'नकद की कमी',
    'Pre-approved Paytm Business Loan': 'प्री-अप्रूव्ड Paytm बिज़नेस लोन',
    Principal: 'मूल राशि',
    'Processing fee': 'प्रोसेसिंग शुल्क',
    'Dismiss order': 'ऑर्डर हटाएं',
    'Forecast': 'फोरकास्ट',
    'Unlock with Premium': 'प्रीमियम से अनलॉक करें',
    '₹499/mo — Tap the plan badge above': '₹499/माह — ऊपर प्लान चुनें',
    Actual: 'वास्तविक',
    'Confidence': 'अनुमान सीमा',
    'Growth insights': 'बिज़नेस इनसाइट्स',
    'Computed from your sales history': 'आपकी बिक्री के आधार पर',
    'Do this:': 'सुझाव:',
    'No notable changes yet.': 'अभी कोई खास बदलाव नहीं।',
    'Forecast performance': 'फोरकास्ट का प्रदर्शन',
    'Accuracy over the last {days} days': 'पिछले {days} दिनों की सटीकता',
    Baseline: 'बेसलाइन',
    'business assumption': 'व्यावसायिक अनुमान',
    'Impact simulator': 'इम्पैक्ट सिम्युलेटर',
    'Illustrative impact: {amount} revenue protected': 'अनुमानित असर: {amount} की बिक्री सुरक्षित',
    '{amount} estimated net gain in {days} days': '{days} दिनों में अनुमानित शुद्ध लाभ {amount}',
    'Based on simulated sales · view assumptions': 'सिम्युलेटेड बिक्री पर आधारित · मान्यताएं देखें',
    'Without Pulse lost revenue:': 'Pulse के बिना खोई बिक्री:',
    'With Pulse lost revenue:': 'Pulse के साथ खोई बिक्री:',
    'Costs:': 'लागत:',
    'Running simulation…': 'सिम्युलेशन चल रहा है…',
    'Why you qualify': 'आप पात्र क्यों हैं',
    'Illustrative terms based on recent sales.': 'हाल की बिक्री पर आधारित अनुमानित शर्तें।',
    'Lending eligibility': 'लोन पात्रता',
    'Illustrative demo terms — not a lending decision.': 'डेमो के लिए अनुमानित शर्तें — यह लोन मंज़ूरी नहीं है।',
    'Pulse execution trace': 'Pulse प्रक्रिया विवरण',
    'A transparent record of the workflow.': 'प्रक्रिया का पूरा विवरण।',
    'Run an analysis to see its trace.': 'विवरण देखने के लिए विश्लेषण चलाएं।',
    'Ask Pulse': 'Pulse से पूछें',
    'What will run out this week?': 'इस हफ्ते किसका स्टॉक खत्म होगा?',
    'Best sellers on Saturday?': 'शनिवार को सबसे ज़्यादा क्या बिकता है?',
    'Which items make the most profit?': 'किन आइटम से सबसे ज़्यादा मुनाफ़ा है?',
    'Computed from your sales data': 'आपकी बिक्री के आधार पर',
    'Upload the documented catalog + sales pair. Demo data stays unchanged.': 'कैटलॉग और बिक्री की CSV अपलोड करें। डेमो डेटा नहीं बदलेगा।',
    'Sales template': 'बिक्री टेम्पलेट',
    'Catalog template': 'कैटलॉग टेम्पलेट',
    'Validate & upload': 'जांचें और अपलोड करें',
    'Simulated supplier order tracking.': 'सप्लायर ऑर्डर की डेमो ट्रैकिंग।',
    'Advance order': 'ऑर्डर आगे बढ़ाएं',
    'Approve a restock plan to see incoming POs.': 'आने वाले ऑर्डर देखने के लिए रीस्टॉक प्लान मंज़ूर करें।',
    'Simulated scheduled decisions; manual analysis always stays human-approved.': 'शेड्यूल किए गए डेमो निर्णय; मैन्युअल ऑर्डर आपकी मंज़ूरी से ही होगा।',
    'Enable Premium rule': 'प्रीमियम नियम चालू करें',
    'Max order ₹{amount}': 'अधिकतम ऑर्डर ₹{amount}',
    'Run now': 'अभी चलाएं',
    Notifications: 'नोटिफिकेशन',
    Home: 'होम',
    Insights: 'इनसाइट्स',
    Accuracy: 'सटीकता',
    Impact: 'इम्पैक्ट',
    Loan: 'लोन',
    Trace: 'विवरण',
    Ask: 'पूछें',
    Supplier: 'सप्लायर',
    Autopilot: 'ऑटोपायलट',
    'My data': 'मेरा डेटा',
    'Reset demo': 'डेमो रीसेट करें',
    Retry: 'फिर कोशिश करें',
    'Failed to load dashboard': 'डैशबोर्ड लोड नहीं हुआ',
    'Demo guide': 'डेमो गाइड',
    'See items at risk': 'जोखिम वाले आइटम देखें',
    'Run the restock analysis': 'रीस्टॉक विश्लेषण चलाएं',
    'Approve the supplier order': 'सप्लायर ऑर्डर मंज़ूर करें',
    'Review the Paytm impact': 'Paytm इम्पैक्ट देखें',
    'Finding growth opportunities…': 'बिक्री के नए मौके देख रहे हैं…',
    'Forecast accuracy': 'फोरकास्ट सटीकता',
    'pts vs baseline': 'अंक बेसलाइन से',
    'vs baseline': 'बेसलाइन से',
    '14-day historical check': 'पिछले 14 दिनों का मिलान',
    forecast: 'फोरकास्ट',
    'Calculating forecast accuracy…': 'फोरकास्ट की सटीकता जांच रहे हैं…',
    'days away': 'दिन बाद',
    'forecast uplift': 'फोरकास्ट में बढ़ोतरी',
    'Pulse order arrival:': 'Pulse ऑर्डर पहुंचेगा:',
    'Reactive order arrival:': 'तुरंत ऑर्डर पहुंचेगा:',
    Repay: 'चुकाएं',
    day: 'दिन',
    'Loan offers are calculated from sales consistency, revenue trend, repayment capacity, and a conservative cap. Terms appear with a restock proposal.': 'लोन ऑफर बिक्री की नियमितता, कमाई के रुझान और चुकाने की क्षमता के आधार पर तय होते हैं। शर्तें रीस्टॉक प्रस्ताव के साथ दिखेंगी।',
    'Distributor portal': 'डिस्ट्रिब्यूटर पोर्टल',
    Status: 'स्थिति',
    delivered: 'पहुंच गया',
    pending: 'लंबित',
    shipped: 'भेज दिया',
    'Interest ({rate}% flat)': 'ब्याज ({rate}% निश्चित)',
    'Repay in {days} days': '{days} दिनों में चुकाएं',
    'Daily settlement deduction': 'रोज़ की भुगतान कटौती',
    'Effective APR (illustrative)': 'अनुमानित सालाना ब्याज दर',
    'Stockout:': 'स्टॉक खत्म होगा:',
    days: 'दिन',
    Items: 'आइटम',
    'Sales rows': 'बिक्री की पंक्तियां',
    'Date range': 'तारीख की सीमा',
    'Upload successful': 'अपलोड सफल रहा',
    'Upload needs attention': 'अपलोड की जांच करें',
    'sales.csv is missing required columns': 'sales.csv में जरूरी कॉलम नहीं हैं',
    'catalog.csv is missing required columns': 'catalog.csv में जरूरी कॉलम नहीं हैं',
    'Invalid sales row for {item}': '{item} की बिक्री वाली पंक्ति अमान्य है',
    'Invalid catalog row for {item}': '{item} की कैटलॉग पंक्ति अमान्य है',
    'Sales item {item} is not in catalog': 'बिक्री का आइटम {item} कैटलॉग में नहीं है',
    '{item} has fewer than 28 sales days; fallback forecast may be used': '{item} के लिए 28 दिनों से कम बिक्री है; वैकल्पिक फोरकास्ट इस्तेमाल हो सकता है',
    'Maximum is 50 SKUs and 50,000 sales rows': 'अधिकतम 50 SKU और बिक्री की 50,000 पंक्तियां अपलोड करें',
    '⚠️ {name} may run out in about {days} days. Restock {count} items for ₹{total}.': '⚠️ {name} का स्टॉक लगभग {days} दिनों में खत्म हो सकता है। ₹{total} में {count} आइटम रीस्टॉक करें।',
    'Loan option: ₹{amount}': 'लोन का विकल्प: ₹{amount}',
    "Loan doesn't fully cover the gap": 'लोन से पूरी कमी नहीं भरेगी',
    '₹{amount} average monthly revenue': 'औसत मासिक बिक्री ₹{amount}',
    'Revenue consistency multiplier {multiplier}': 'बिक्री की नियमितता का गुणक {multiplier}',
    'Need at least 60 days of sales': 'कम से कम 60 दिनों की बिक्री का डेटा चाहिए',
    'Recent revenue trend reduced the limit': 'हाल की बिक्री के रुझान से सीमा कम हुई',
    'Calculated limit is below ₹5,000': 'गणना की गई सीमा ₹5,000 से कम है',
    'Lead time': 'सप्लाई में लगने वाला समय',
    'Lead time + 1 day': 'सप्लाई में लगने वाला समय + 1 दिन',
    'View assumptions': 'मान्यताएं देखें',
    'Paytm Business · Simulated notification': 'Paytm Business · डेमो नोटिफिकेशन',
    'Sales': 'बिक्री',
    Revenue: 'बिक्री',
    'Language': 'भाषा',
    'No sales in 14 days': '14 दिनों में बिक्री नहीं',
    'Move it with a bundle or discount.': 'इसे ऑफर या छूट के साथ बेचें।',
    '~{days} days of stock': 'लगभग {days} दिन का स्टॉक',
    'Pause reordering {name}.': '{name} का नया ऑर्डर रोकें।',
    '+{change}% revenue vs last week': 'पिछले हफ्ते से बिक्री {change}% बढ़ी',
    '{change}% revenue vs last week': 'पिछले हफ्ते से बिक्री {change}% बदली',
    'Keep this item visible and in stock.': 'इस आइटम को दिखने वाली जगह रखें और स्टॉक बनाए रखें।',
    'Check pricing and shelf placement.': 'कीमत और शेल्फ की जगह जांचें।',
    '{day} is your strongest day': '{day} आपकी सबसे अच्छी बिक्री का दिन है',
    '{day} needs attention': '{day} पर ध्यान दें',
    '₹{amount} average revenue': 'औसत बिक्री ₹{amount}',
    'Stock up before {day}.': '{day} से पहले स्टॉक बढ़ाएं।',
    'Run a promo on {day}.': '{day} को ऑफर चलाएं।',
    '₹{amount} gross profit ({share}%)': 'सकल मुनाफ़ा ₹{amount} ({share}%)',
    'Protect availability of this profitable item.': 'इस मुनाफ़ेदार आइटम का स्टॉक बनाए रखें।',
    '₹{amount}/unit margin': '₹{amount}/यूनिट मार्जिन',
    'Promote {name}.': '{name} का प्रचार करें।',
    'Cash tied up in inventory': 'स्टॉक में फंसा नकद',
    'Use slow-stock promotions to release working capital.': 'धीमे बिकने वाले स्टॉक पर ऑफर देकर नकदी वापस लाएं।',
    'Items at risk:': 'जोखिम वाले आइटम:',
    'No items are currently at risk.': 'अभी कोई आइटम जोखिम में नहीं है।',
    'Top profit item: {name} (₹{amount}).': 'सबसे मुनाफ़ेदार आइटम: {name} (₹{amount})।',
    'Best seller on Saturday: {name} ({units} units).': 'शनिवार का सबसे ज़्यादा बिकने वाला आइटम: {name} ({units} यूनिट)।',
    'Best seller: {name} at ₹{amount} in sales.': 'सबसे ज़्यादा बिक्री: {name}, ₹{amount}।',
    'Loaded inventory risk': 'इन्वेंटरी जोखिम की जांच हुई',
    'Drafted supplier purchase orders': 'सप्लायर ऑर्डर का ड्राफ्ट बना',
    'Checked cash and loan eligibility': 'नकद और लोन पात्रता जांची गई',
    'Prepared merchant alert': 'दुकानदार के लिए अलर्ट तैयार हुआ',
    'Saved approval proposal': 'मंज़ूरी का प्रस्ताव सेव हुआ',
    'Waiting for merchant approval': 'दुकानदार की मंज़ूरी का इंतज़ार',
    'Orders placed and funding processed': 'ऑर्डर भेजे और फंडिंग पूरी हुई',
    'Orders placed · loan disbursed': 'ऑर्डर भेजे · लोन जारी हुआ',
    'Pulse analyzed today’s inventory': 'Pulse ने आज की इन्वेंटरी जांची',
    'Auto-approved by your rule': 'आपके नियम से अपने-आप मंज़ूर हुआ',
    load_and_select: 'स्टॉक जोखिम की जांच',
    draft_po: 'सप्लायर ऑर्डर का ड्राफ्ट',
    check_cash: 'नकद और लोन पात्रता की जांच',
    write_alert: 'दुकानदार के लिए अलर्ट',
    save_proposal: 'मंज़ूरी का प्रस्ताव सेव',
    await_approval: 'दुकानदार की मंज़ूरी का इंतज़ार',
    execute: 'ऑर्डर और फंडिंग पूरी',
    decision: 'निर्णय',
    Monday: 'सोमवार',
    Tuesday: 'मंगलवार',
    Wednesday: 'बुधवार',
    Thursday: 'गुरुवार',
    Friday: 'शुक्रवार',
    Saturday: 'शनिवार',
    Sunday: 'रविवार',
    Next: 'आगे',
    Finish: 'पूरा करें',
  },
  hinglish: {
    Demo: 'Demo',
    'Store desk': 'Store desk',
    'Available cash': 'Available cash',
    Free: 'Free',
    'Tap to upgrade · ₹499/mo': 'Upgrade karein · ₹499/mahina',
    'My store': 'Mera store',
    'Demo store': 'Demo store',
    'Store overview': 'Store ka overview',
    'Your business at a glance': 'Business ki ek nazar',
    'Needs attention': 'Dhyan dena hai',
    'On track': 'Sab theek hai',
    'Revenue at risk': 'Risk mein sales',
    'Potential sales · next 7 days': 'Possible sales · agle 7 din',
    'Items at risk': 'Risk wale items',
    'Stock may run low soon': 'Stock jaldi kam ho sakta hai',
    'All listed items look covered': 'Sabhi items ka stock theek hai',
    'Daily revenue': 'Roz ki sales',
    'A two-week view of your sales': 'Pichhle 14 din ki sales',
    '14 days': '14 din',
    'Create restock plan': 'Restock plan banayein',
    'Preparing your restock plan…': 'Restock plan ready ho raha hai…',
    'Restock plan ready — review the suggested order below': 'Restock plan ready hai — neeche order review karein',
    'All items are well-stocked!': 'Sabhi items ka stock theek hai!',
    'Analysis failed': 'Analysis complete nahi hua',
    'Approval failed': 'Order approve nahi hua',
    'Rejection failed': 'Order reject nahi hua',
    'Plan update failed': 'Plan update nahi hua',
    'Reset failed': 'Demo reset nahi hua',
    'Orders placed with {count} distributor(s) ✓': '{count} supplier ko order bheja ✓',
    ' · Loan ₹{amount} disbursed ✓': ' · ₹{amount} ka loan release hua ✓',
    ' · Cash ₹{amount}': ' · Cash ₹{amount}',
    'Demo reset ✓': 'Demo reset ho gaya ✓',
    'Premium activated! ₹499/mo': 'Premium activate hua! ₹499/mahina',
    'Switched to Free plan': 'Free plan par switch kiya',
    '{day} is your strongest day': '{day} sabse achhi sales ka din hai',
    '{day} needs attention': '{day} par dhyan dena hai',
    'No sales in 14 days': '14 din se sales nahi hui',
    'Move it with a bundle or discount.': 'Bundle ya discount ke saath bechein.',
    '~{days} days of stock': 'Lagbhag {days} din ka stock',
    'Pause reordering {name}.': '{name} ka naya order rok dein.',
    '+{change}% revenue vs last week': 'Pichhle hafte se sales {change}% badhi',
    '{change}% revenue vs last week': 'Pichhle hafte se sales {change}% badli',
    'Keep this item visible and in stock.': 'Is item ko visible rakhein aur stock maintain karein.',
    'Check pricing and shelf placement.': 'Price aur shelf placement check karein.',
    '₹{amount} average revenue': 'Average sales ₹{amount}',
    'Stock up before {day}.': '{day} se pehle stock badhayein.',
    'Run a promo on {day}.': '{day} ko offer chalayein.',
    '₹{amount} gross profit ({share}%)': 'Gross profit ₹{amount} ({share}%)',
    'Protect availability of this profitable item.': 'Is profitable item ka stock maintain karein.',
    '₹{amount}/unit margin': '₹{amount}/unit margin',
    'Promote {name}.': '{name} ko promote karein.',
    'Cash tied up in inventory': 'Inventory mein cash atka hua hai',
    'Use slow-stock promotions to release working capital.': 'Slow-moving stock par offers dekar working cash release karein.',
    'Items at risk:': 'Risk wale items:',
    'No items are currently at risk.': 'Abhi koi item risk mein nahi hai.',
    'Top profit item: {name} (₹{amount}).': 'Sabse profitable item: {name} (₹{amount}).',
    'Best seller on Saturday: {name} ({units} units).': 'Saturday ka best seller: {name} ({units} units).',
    'Best seller: {name} at ₹{amount} in sales.': 'Best seller: {name}, ₹{amount} ki sales.',
    'Loaded inventory risk': 'Inventory risk check hua',
    'Drafted supplier purchase orders': 'Supplier order draft bana',
    'Checked cash and loan eligibility': 'Cash aur loan eligibility check hui',
    'Prepared merchant alert': 'Merchant alert ready hua',
    'Saved approval proposal': 'Approval proposal save hua',
    'Waiting for merchant approval': 'Merchant approval ka wait hai',
    'Orders placed and funding processed': 'Orders place hue aur funding process hui',
    'Orders placed · loan disbursed': 'Orders place hue · loan release hua',
    'Pulse analyzed today’s inventory': 'Pulse ne aaj ki inventory check ki',
    'Auto-approved by your rule': 'Aapke rule se auto-approve hua',
    'Question is required': 'Sawaal zaroori hai',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
    Sunday: 'Sunday',
    'Proposal dismissed': 'Proposal hata diya',
    'Analysis complete — review the restock alert below': 'Analysis complete — neeche restock alert review karein',
    'this week': 'is hafte',
    'of {total} total': 'total {total} mein se',
    Inventory: 'Inventory',
    'Tap an item to view its forecast': 'Forecast dekhne ke liye item chunein',
    '{count} items': '{count} items',
    Incoming: 'Aa raha hai',
    'Out tomorrow!': 'Kal stock khatam!',
    '≈{days} days': 'lagbhag {days} din',
    'arriving {date}': '{date} ko aayega',
    'Restock alert': 'Restock alert',
    'Review your suggested order': 'Suggested order check karein',
    'Preview notification': 'Notification dekhein',
    Listen: 'Sunein',
    'Order ₹{amount}': 'Order ₹{amount}',
    Dismiss: 'Hataein',
    'Approve & Fund': 'Approve karein',
    'Placing orders…': 'Orders place ho rahe hain…',
    'Order Details': 'Order ki details',
    Subtotal: 'Subtotal',
    'Platform fee (1%)': 'Platform fee (1%)',
    Total: 'Total',
    'Cash available': 'Available cash',
    'Cash gap': 'Cash ki kami',
    'Pre-approved Paytm Business Loan': 'Pre-approved Paytm Business Loan',
    Principal: 'Principal amount',
    'Processing fee': 'Processing fee',
    Forecast: 'Forecast',
    'Unlock with Premium': 'Premium se unlock karein',
    '₹499/mo — Tap the plan badge above': '₹499/mahina — upar plan par tap karein',
    Actual: 'Actual',
    Confidence: 'Confidence range',
    'Growth insights': 'Business insights',
    'Computed from your sales history': 'Aapki sales history se',
    'Do this:': 'Yeh karein:',
    'No notable changes yet.': 'Abhi koi khaas badlav nahi.',
    'Forecast performance': 'Forecast performance',
    'Accuracy over the last {days} days': 'Pichhle {days} din ki accuracy',
    Baseline: 'Baseline',
    'business assumption': 'business assumption',
    'Impact simulator': 'Impact simulator',
    'Illustrative impact: {amount} revenue protected': 'Estimated impact: {amount} sales protected',
    '{amount} estimated net gain in {days} days': '{days} din mein estimated net gain {amount}',
    'Based on simulated sales · view assumptions': 'Simulated sales par based · assumptions dekhein',
    'Without Pulse lost revenue:': 'Pulse ke bina lost revenue:',
    'With Pulse lost revenue:': 'Pulse ke saath lost revenue:',
    'Costs:': 'Costs:',
    'Running simulation…': 'Simulation chal raha hai…',
    'Why you qualify': 'Aap eligible kyun hain',
    'Illustrative terms based on recent sales.': 'Recent sales par based estimated terms.',
    'Lending eligibility': 'Loan eligibility',
    'Illustrative demo terms — not a lending decision.': 'Demo terms — loan approval nahi hai.',
    'Pulse execution trace': 'Pulse process details',
    'A transparent record of the workflow.': 'Workflow ka clear record.',
    'Run an analysis to see its trace.': 'Details dekhne ke liye analysis chalayein.',
    'Ask Pulse': 'Pulse se poochhein',
    Ask: 'Poochhein',
    'What will run out this week?': 'Is hafte kis item ka stock khatam hoga?',
    'Best sellers on Saturday?': 'Saturday ko best sellers kaun se hain?',
    'Which items make the most profit?': 'Kaun se items se sabse zyada profit hai?',
    'Computed from your sales data': 'Aapki sales data se calculate hua',
    'My data': 'Mera data',
    'Upload the documented catalog + sales pair. Demo data stays unchanged.': 'Catalog aur sales CSV upload karein. Demo data same rahega.',
    'Sales template': 'Sales template',
    'Catalog template': 'Catalog template',
    'Validate & upload': 'Check karke upload karein',
    'Distributor portal': 'Supplier portal',
    'Simulated supplier order tracking.': 'Supplier order ki demo tracking.',
    'Advance order': 'Order aage badhayein',
    'Approve a restock plan to see incoming POs.': 'Incoming orders dekhne ke liye restock plan approve karein.',
    Autopilot: 'Autopilot',
    'Simulated scheduled decisions; manual analysis always stays human-approved.': 'Scheduled demo decisions; manual orders aapki approval se hi honge.',
    'Enable Premium rule': 'Premium rule enable karein',
    'Max order ₹{amount}': 'Max order ₹{amount}',
    'Run now': 'Abhi chalayein',
    Notifications: 'Notifications',
    Home: 'Home',
    Insights: 'Insights',
    Accuracy: 'Accuracy',
    Impact: 'Impact',
    Loan: 'Loan',
    Trace: 'Trace',
    Supplier: 'Supplier',
    'Reset demo': 'Demo reset karein',
    Retry: 'Dobara try karein',
    'Failed to load dashboard': 'Dashboard load nahi hua',
    'Demo guide': 'Demo guide',
    'See items at risk': 'Risk wale items dekhein',
    'Run the restock analysis': 'Restock analysis chalayein',
    'Approve the supplier order': 'Supplier order approve karein',
    'Review the Paytm impact': 'Paytm impact dekhein',
    Next: 'Aage',
    Finish: 'Complete',
    'Finding growth opportunities…': 'Sales ke naye mauke dekh rahe hain…',
    'Forecast accuracy': 'Forecast accuracy',
    'pts vs baseline': 'points baseline se',
    'vs baseline': 'baseline se',
    '14-day historical check': 'Pichhle 14 din ka check',
    forecast: 'forecast',
    'Calculating forecast accuracy…': 'Forecast accuracy calculate ho rahi hai…',
    'days away': 'din baad',
    'forecast uplift': 'forecast mein badhotri',
    'Pulse order arrival:': 'Pulse order pahunchega:',
    'Reactive order arrival:': 'Turant order pahunchega:',
    Repay: 'Chukayein',
    day: 'din',
    'Loan offers are calculated from sales consistency, revenue trend, repayment capacity, and a conservative cap. Terms appear with a restock proposal.': 'Loan offer regular sales, revenue trend aur repayment capacity ke basis par calculate hota hai. Terms restock proposal ke saath dikhenge.',
    Status: 'Status',
    delivered: 'Pahunch gaya',
    pending: 'Pending',
    shipped: 'Bhej diya',
    'Interest ({rate}% flat)': 'Interest ({rate}% fixed)',
    'Repay in {days} days': '{days} din mein repay karein',
    'Daily settlement deduction': 'Daily payment deduction',
    'Effective APR (illustrative)': 'Estimated yearly interest rate',
    'Stockout:': 'Stock khatam hoga:',
    days: 'din',
    Items: 'Items',
    'Sales rows': 'Sales rows',
    'Date range': 'Date range',
    'Upload successful': 'Upload successful',
    'Upload needs attention': 'Upload mein issue hai',
    'sales.csv is missing required columns': 'sales.csv mein zaroori columns nahi hain',
    'catalog.csv is missing required columns': 'catalog.csv mein zaroori columns nahi hain',
    'Invalid sales row for {item}': '{item} ki sales row sahi nahi hai',
    'Invalid catalog row for {item}': '{item} ki catalog row sahi nahi hai',
    'Sales item {item} is not in catalog': 'Sales item {item} catalog mein nahi hai',
    '{item} has fewer than 28 sales days; fallback forecast may be used': '{item} ki sales 28 din se kam hai; alternate forecast use ho sakta hai',
    'Maximum is 50 SKUs and 50,000 sales rows': 'Maximum 50 SKU aur 50,000 sales rows upload karein',
    '⚠️ {name} may run out in about {days} days. Restock {count} items for ₹{total}.': '⚠️ {name} ka stock lagbhag {days} din mein khatam ho sakta hai. ₹{total} mein {count} items restock karein.',
    'Loan option: ₹{amount}': 'Loan ka option: ₹{amount}',
    "Loan doesn't fully cover the gap": 'Loan se poora gap cover nahi hoga',
    '₹{amount} average monthly revenue': 'Average monthly sales ₹{amount}',
    'Revenue consistency multiplier {multiplier}': 'Sales consistency multiplier {multiplier}',
    'Need at least 60 days of sales': 'Kam se kam 60 din ka sales data chahiye',
    'Recent revenue trend reduced the limit': 'Recent sales trend se limit kam hui',
    'Calculated limit is below ₹5,000': 'Calculated limit ₹5,000 se kam hai',
    'Lead time': 'Supplier se aane ka time',
    'Lead time + 1 day': 'Supplier se aane ka time + 1 din',
    'Paytm Business · Simulated notification': 'Paytm Business · Demo notification',
    Revenue: 'Sales',
    Language: 'Language',
    load_and_select: 'Inventory risk check',
    draft_po: 'Supplier order ka draft',
    check_cash: 'Cash aur loan eligibility check',
    write_alert: 'Merchant alert',
    save_proposal: 'Approval proposal save',
    await_approval: 'Merchant approval ka wait',
    execute: 'Orders aur funding complete',
    decision: 'Decision',
  },
}

export function translate(language, key, values = {}) {
  let result = strings[language]?.[key] ?? key
  for (const [name, value] of Object.entries(values)) {
    result = result.replaceAll(`{${name}}`, String(value))
  }
  return result
}
